# Generated by Django 4.2.2 on 2023-07-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_inventory_in_hand_list_of_po_iteams_vendor_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='serial_number',
            field=models.IntegerField(unique=True),
        ),
    ]
