<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-07-02 13:38
=======
# Generated by Django 4.2.3 on 2023-07-03 17:34
>>>>>>> dd9efee4d5d54d44a0ff8b1530dfc7b8888b10ae

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_details_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_po_iteams',
            name='po_id',
            field=models.IntegerField(unique=True),
        ),
    ]
