# Generated by Django 4.2.3 on 2023-07-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_details_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_po_iteams',
            name='po_id',
            field=models.IntegerField(unique=True),
        ),
    ]
